### PR TITLE
Add a classNameMatcher option to make component resolution more flexible

### PR DESCRIPTION
**Pull request by vieron**
Hi!

This change would be super helpful for libraries like UI kits where all components extend from a common base class.

If you are ok with adding this extra option, I could write a test for it.

Thanks!

### CODE REVIEW

**Comment by oliviertassinari** [comment]
@vieron I'm happy with the idea. I have one concern with the API.
> You could also pass a regex to match multiple components like "BaseComponent|PrivateComponent".

The `ignoreFilenames` option solve the same problem differently. What about being systematic?

**Comment by vieron** [comment]
@oliviertassinari makes sense, I didn't realize of this implementation in `ignoreFileNames`.

I will try to find some time between today and tomorrow to get this done.

**Comment by vieron** [comment]
Ok @oliviertassinari, I finally got some free time to finish this! This is ready to review :)

**Comment by oliviertassinari** [comment]
I will do a release later today.

**Comment by vieron** [comment]
Thanks!

**Pull request merged**
