### PR TITLE
feat(lib): add a wrap-safe mode

### LINKED ISSUE #95: Instead of removing propTypes, replace with empty object
Removing propTypes entirely is causing issues with third party dependencies that need them to be defined. This was causing issues when using [react-native-web](https://github.com/necolas/react-native-web/issues/423#issuecomment-293620555).

It was brought up that replacing propTypes with an empty object would have the effects of not needing those definitions, while allowing libraries to reference undefined properties on propTypes and prevent `cannot read [name] of undefined` errors.

### PR DESCRIPTION
**Pull request by oliviertassinari**
Closes #95. Thanks @ndbroadbent for the inspiration.

### CODE REVIEW

**Comment by ndbroadbent** [comment]
That's awesome, thanks @oliviertassinari!

**Comment by necolas** [comment]
Why introduce a new option rather than adjust the existing one?

**Comment by oliviertassinari** [comment]
Because I want to keep the same behavior for Material-UI. I think that the issue is specific to the react native ecosystem. I would rather have lib author choose what's the best tradeoff for them.

**Comment by necolas** [comment]
I don't see how it's specific to React Native. You can encounter this error when trying to access props types from any component exported by any React library built using `wrap` mode, including Material-UI.

```js
// library button using 'wrap' mode
const Button = () => {}
Button.propTypes = { color: ColorPropType }

// app not using react-remove-prop-types plugin; throws Error in production build
const CustomButton = () => {}
CustomButton.propTypes = { color: Button.propTypes.color }
```

My suggestion would be to change `wrap` mode to include this fix (easiest way to fix any problematic libraries out there); and if you need another mode for Material-UI call it `unsafe-wrap` to communicate that it causes errors in some circumstances.

**Comment by oliviertassinari** [comment]
I think that it's specific to React Native in the sense of pattern promoted by the core components. Like documenting `View.propTypes.style`. We have been using this plugin on Material-UI for months. Nobody complained about it.

We can try that.

**Pull request merged**
