### PR TITLE
Add handling for removing propTypes for React.Memo component with implicitly returned

### LINKED ISSUE #196: Doesn’t remove propTypes in certain situations
For all of the following examples, `propTypes` are incorrectly not removed:

```jsx
import PropTypes from 'prop-types';

export default function Foo({ children }) {
  return children();
}

Foo.propTypes = {
  children: PropTypes.func.isRequired,
};
```

[Babel REPL](https://babeljs.io/repl#?code_lz=JYWwDg9gTgLgBABShMAVAnmApgZzgM2RDgHIxkwBaGTXEgbgChGsAPSWOAEy3wEMArgBt4-AQDsAxjGARxcAGIQIACgDecSQAtgQrlCzyAvgEo4axnDgGYAqPO279hlSaZHmSiADpyKDNh4ALzmlpo6egbiAFyIFAG43mJSADSMRkxAA&sourceType=module&lineWrap=false&presets=react&prettier=true&version=7.11.6&externalPlugins=babel-plugin-transform-react-remove-prop-types%400.4.24)

```jsx
import PropTypes from 'prop-types';

export default function Foo({ children }) {
  return children;
}

Foo.propTypes = {
  children: PropTypes.node,
};
```

```jsx
import PropTypes from 'prop-types';

export default function Foo({ children }) {
  return <>{children}</>;
}

Foo.propTypes = {
  children: PropTypes.node,
};
```

While this works:

```jsx
import PropTypes from 'prop-types';

export default function Foo({ children }) {
  return <div>{children}</div>;
}

Foo.propTypes = {
  children: PropTypes.node,
};
```

### PR DESCRIPTION
**Pull request by leusrox**
Closes https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/issues/196#issuecomment-857658735

### CODE REVIEW

**Review by oliviertassinari — APPROVED** [review]

**Comment by leusrox** [comment]
Hi **[@oliviertassinari](https://github.com/oliviertassinari)**! The tests is passed 🎉
Could you look again, please?

**Comment by leusrox** [comment]
@oliviertassinari Sorry for the intrusiveness, but is it possible to publish a patch for this fix? We'd like to include this into our build because it will help to remove propTypes for many components.

**Comment by leusrox** [comment]
> @oliviertassinari Sorry for the intrusiveness, but is it possible to publish a patch for this fix? We'd like to include this into our build because it will help to remove propTypes for many components.

Bump 😊

**Comment by jsmecham** [comment]
@oliviertassinari Any chance of cutting a release containing this?

**Pull request merged**
