### PR TITLE
stateless components that return React.createElement

### PR DESCRIPTION
**Pull request by NogsMPLS**
adding functionality for stateless components that return ```React.createElement```

### CODE REVIEW

**Comment by oliviertassinari** [comment]
@NogsMPLS All tests are green, thanks :+1:. However, I'm gonna change your code and add some tests. There is some edge cases that don't work.

**Comment by NogsMPLS** [comment]
sounds good! I'll be keeping an eye on the changes you make so i can put them in my repo: https://github.com/NogsMPLS/babel-plugin-transform-react-remove-statics

**Comment by oliviertassinari** [comment]
For instance:
```jsx
const Foo9 = () => (
  React.createElement("div", null)
);

Foo9.propTypes = {
  foo: React.PropTypes.string
};
```

**Comment by NogsMPLS** [comment]
yeah, also should put in something in case if createElement is destructured out of import like:

```import { createElement } from "react"```

**Pull request merged**
