### PR TITLE
Use babel-traverse from the Babel object

### PR DESCRIPTION
**Pull request by vlad-zhukov**

### CODE REVIEW

**Comment by oliviertassinari** [comment]
@vlad-zhukov Thanks!

**Comment by oliviertassinari** [comment]
This will help with the upcoming babel release.

**Comment by vlad-zhukov** [comment]
@oliviertassinari Thanks! I am working on Babel 7 support right now.

**Comment by iamstarkov** [comment]
@vlad-zhukov @oliviertassinari does it still work with babel 6?

**Comment by oliviertassinari** [comment]
@iamstarkov Yes, it does.

**Comment by iamstarkov** [comment]
@oliviertassinari thanks

**Pull request merged**
