### PR TITLE
fix: more aggressive remove-proptypes exploration

### LINKED ISSUE #106: propTypes not removed for HOC
Hello,
I've just installed this and it seems that for my edge cases this is not working. 

The following propTypes are not removed from the build. While all the others declared in the _standard_ way are correctly removed.

**CASE 1**:
```
const myPropName = 'whatever';
BaseLink.propTypes = {
  prop1: PropTypes.string
  prop2: PropTypes.node
};

BaseLink.propTypes[myPropName] = PropTypes.object;  //<== This is not removed
```

**CASE 2**:
```
const myPropName = 'whatever';
// Both are not removed
MyComp.wrappedComponent.propTypes = {};
MyComp.wrappedComponent.propTypes[myPropName] = PropTypes.object.isRequired;
```
Here I used wrappedComponents, because I'm decorating my original component `MyComp` with mobx-react [@observer](https://github.com/mobxjs/mobx-react#provider-and-inject) that will indeed create a new wrapper. So the original component is available as `MyComp.wrappedComponent`.

**CASE 3**:
This applies to both cases above. 
I'm importing my PropTypes from the [new separate packages](https://www.npmjs.com/package/prop-types)

```
import PropTypes from 'prop-types';
```
It seems the import is never removed from the build using the default config (supposed to be `remove` mode).

I'm not sure if this is due to the 2 cases above (still having some `propTypes` in the build would not allow to remove the import?) or because I import them from the separate package and not from the React core... 🤔

### PR DESCRIPTION
**Pull request by oliviertassinari**
Closes #106.

### CODE REVIEW

**Comment by LeonardoGentile** [comment]
👍  thanks, is this released on npm already?

**Comment by oliviertassinari** [comment]
It's on npm now.

**Comment by LeonardoGentile** [comment]
@oliviertassinari I've just installed and retried the use cases listed on #106  and nothing changed from my perspective. The propTypes mentioned in the issue keeps on living in the compiled code, they are never removed, also the import is never removed as well

**Comment by LeonardoGentile** [comment]
Also adding the special comments for helping the plugin has no effect at all:
```
BaseLink.propTypes[storeName] /* remove-proptypes */ = PropTypes.object;
```

**Comment by oliviertassinari** [comment]
I'm not supporting that pattern, have a look at the test case.

**Comment by oliviertassinari** [comment]
> also the import is never removed as well

From my understanding of the situation, you are shipping a library, you can to keep it so users get warning in dev mode.

**Comment by LeonardoGentile** [comment]
👍  thanks for the suggestion, I wasn't aware of es6 object dynamic keys, that solve the problem I was trying to fix. 

I will ship the PropTypes then as you suggested. 

I've made a local test with your suggestion and I can confirm that it fixes the problem, all the proptypes are removed as well as the import.

Thanks 👍

**Comment by oliviertassinari** [comment]
Awesome 😄 , unless you noticed it, the test case is using the `wrap` mode. I would encourage you doing the same. Here the [docs](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types#mode).

**Pull request merged**
