### PR TITLE
core(babel): upgrade to @babel latest beta

### PR DESCRIPTION
**Pull request by oliviertassinari**
@danez I'm close, now I have the `Error: No substitution given for "NODE_ENV"` error :).

### CODE REVIEW

**Comment by danez** [comment]
´babel-plugin-transform-class-properties´ is now ´@babel/plugin-proposal-class-properties´

**Comment by oliviertassinari** [comment]
I will wait for the new beta release.

**Comment by danez** [comment]
I opened a PR  for this PR. The current beta already includes everything it just seems that the we all misunderstood how the whitelist works. It is merely an additional whitelist to the regular crawling and not the single source of placeholders.

**Comment by insin** [comment]
Is this a breaking change or is it backwards-compatible for use with Babel 6?

**Comment by oliviertassinari** [comment]
@insin It's backwards-compatible.

**Pull request merged**
